ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pendingEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailTokenExpiry" TIMESTAMP(3);
